(function($) {
    var loadConfig_default_settings = {
        //"curVersion": "3.0",
        "curUser": { Name: "Unknown", Department: "Unknown" },
        //"history-count": 10,
        //"testcase-count": 10,
        ////以下仅无DB时测试用
        "fromDB": false,
        //"local_history_newid": 1,
        //"local_testcase_newid": 1,
        //"local_package_newid": 1
        config_service: {
            product: ["credis", "cmemcache"],
            configapi_cluster: {
                credis: { id: "", name: "credis_configapi集群", desc: "", cluster: "", ip: ["10.2.6.22", "10.2.6.40"] },
            },
            credis_configapi: [{
                url: "http://ws.fx.fws.qa.nt.ctripcorp.com/credis/configapi/getcluster",
                name: "getcluster",
                desc: "获取集群信息",
                label: [],
                method: "GET",
                //contentType: "application/json;charset=utf-8",
                params: [{
                    name: "ClusterName",
                    handler: "UrlAppend",
                    default_value: "/SentinelTest0",
                    options: [{ name: "/SentinelTest0", desc: "SentinelTest0", value: "/SentinelTest0" },
                        { name: "/SentinelTest0/shafq", desc: "SentinelTest0-福泉", value: "/SentinelTest0/shafq" },
                        { name: "/SentinelTest0/shajq", desc: "SentinelTest0-金桥", value: "/SentinelTest0/shajq" },
                        { name: "/SentinelTest0/shaoy", desc: "SentinelTest0-欧阳", value: "/SentinelTest0/shaoy" }
                    ]
                }]
            }, {
                url: "http://ws.fx.fws.qa.nt.ctripcorp.com/credis/configapi/getidc",
                name: "getidc",
                desc: "",
                label: ["getidc"],
                method: "GET"
            }, {
                url: "http://ws.fx.fws.qa.nt.ctripcorp.com/credis/configapi/getidcs",
                name: "getidcs",
                desc: "",
                label: ["getidc"],
                method: "GET"
            }, {
                url: "http://ws.fx.fws.qa.nt.ctripcorp.com/credis/configapi/updatecache",
                name: "updatecache",
                desc: "",
                label: [],
                method: "GET"
            }]
        },
        config_idc: {
            "SHAFQ": { name: "FQ-福泉" },
            "SHAJQ": { name: "JQ-金桥"},
            "SHAOY": { name: "OY-欧阳"},
            "NONE": { name: "无IDC" }
        },
        config_productline: [
            { id: 42, name: "AccFlight" },
            { id: 44, name: "AccCash" },
            { id: 121, name: "用车产品线" },
            { id: 122, name: "网站运营产品线" },
            { id: 124, name: "机酒产品线" },
            { id: 125, name: "高端产品线" },
            { id: 126, name: "地面产品线" },
            { id: 127, name: "机票产品线" },
            { id: 130, name: "03框架独立产品" },
            { id: 131, name: "酒店产品线" },
            { id: 133, name: "团购产品线" },
            { id: 134, name: "01火车票" },
            { id: 135, name: "购物产品线" },
            { id: 136, name: "01团队游" },
            { id: 138, name: "02保险" },
            { id: 140, name: "景酒产品线" },
            { id: 141, name: "01攻略" },
            { id: 144, name: "04数据类" },
            { id: 146, name: "01支付" },
            { id: 147, name: "01消费金融" },
            { id: 149, name: "01用户中心" },
            { id: 151, name: "03基础产品" },
            { id: 152, name: "04呼叫中心" },
            { id: 153, name: "01服务产品" },
            { id: 154, name: "06无线产品" },
            { id: 155, name: "系统研发产品线" },
            { id: 158, name: "01分销" },
            { id: 159, name: "02营销" },
            { id: 165, name: "主题旅游产品线" },
            { id: 166, name: "搜索产品线" },
            { id: 169, name: "国际业务产品线" },
            { id: 170, name: "风险控制产品线" },
            { id: 171, name: "商旅产品线" },
            { id: 174, name: "05商旅用户&公共" },
            { id: 176, name: "邮轮产品线" },
            { id: 177, name: "金融平台产线" },
            { id: 178, name: "汽车票产品线" },
            { id: 182, name: "海外业务产品线" },
            { id: 184, name: "02无线学生版" },
            { id: 185, name: "01包团定制" },
            { id: 187, name: "03周末出游" },
            { id: 190, name: "02Application" },
            { id: 196, name: "05收单系统" },
            { id: 197, name: "05数据产品和服务" },
            { id: 198, name: "信息安全产品线" },
            { id: 205, name: "06金融创新" },
            { id: 4302, name: "Account.Corp" }
        ],
        config_cluster: [
{ pid: 42, name: "SentinelTest2" },
{ pid: 44, name: "frtlocal_Product_BaseData" },
{ pid: 121, name: "SentinelTest0" },
{ pid: 121, name: "zy_yan" },
{ pid: 121, name: "CarCache" },
{ pid: 121, name: "carcache1" },
{ pid: 121, name: "carcache2" },
{ pid: 121, name: "carcache3" },
{ pid: 121, name: "carcache4" },
{ pid: 121, name: "carcache5" },
{ pid: 121, name: "carcache6" },
{ pid: 121, name: "carcache7" },
{ pid: 121, name: "carcache8" },
{ pid: 121, name: "carcache9" },
{ pid: 121, name: "Carcache10" },
{ pid: 121, name: "Carcache11" },
{ pid: 121, name: "Carcache12" },
{ pid: 121, name: "Carcache13" },
{ pid: 121, name: "Carcache14" },
{ pid: 121, name: "Carcache15" },
{ pid: 121, name: "Carcache17" },
{ pid: 121, name: "Carcache18" },
{ pid: 121, name: "Carcache19" },
{ pid: 121, name: "Carcache16" },
{ pid: 121, name: "frt-closed-schedule" },
{ pid: 121, name: "SentinelTest" },
{ pid: 122, name: "RatTest" },
{ pid: 122, name: "ops_saltcache" },
{ pid: 122, name: "CMSSession" },
{ pid: 124, name: "FRTEventCache" },
{ pid: 124, name: "frtquerycache" },
{ pid: 124, name: "frtpricejob" },
{ pid: 124, name: "frtproductservice" },
{ pid: 124, name: "frtpriceTask" },
{ pid: 124, name: "frtbookingSearch" },
{ pid: 124, name: "frt_Product_BaseData" },
{ pid: 124, name: "frt_shopping" },
{ pid: 124, name: "frt_booking" },
{ pid: 124, name: "frt-price-engine" },
{ pid: 124, name: "shx-supplier" },
{ pid: 124, name: "frt_product_schedule" },
{ pid: 124, name: "frt_aggregation_productbasic" },
{ pid: 125, name: "hhtravel" },
{ pid: 126, name: "VIP_Actws" },
{ pid: 126, name: "RedisTTDPromotion" },
{ pid: 126, name: "RedisACTPromotion" },
{ pid: 126, name: "GSCommonDynamicDataCache" },
{ pid: 126, name: "RedisTTDProduct" },
{ pid: 126, name: "RedisACTProduct" },
{ pid: 126, name: "VIP_Ttdws" },
{ pid: 126, name: "ttd_search" },
{ pid: 126, name: "ttd_bi" },
{ pid: 126, name: "Ttd_monitor" },
{ pid: 126, name: "ttd_product_act" },
{ pid: 126, name: "ttd_arch_app" },
{ pid: 127, name: "FltLowPriceRedis" },
{ pid: 127, name: "FlightIntlOnlineBaseDataCache" },
{ pid: 127, name: "FlightAggregatorSalesPolicyCache" },
{ pid: 127, name: "FltCoreSearchRedis" },
{ pid: 127, name: "OAGFlightScheduleDataCache" },
{ pid: 127, name: "FlightTicket" },
{ pid: 127, name: "FltSPDBRedis" },
{ pid: 127, name: "IntFarePlatform" },
{ pid: 127, name: "FlightTradeConnectivity" },
{ pid: 127, name: "FlightIntlFlashSalesCache" },
{ pid: 127, name: "FlightUserPreferencesCache" },
{ pid: 127, name: "FlightIntlSaleProhibitCached" },
{ pid: 127, name: "IntlFlight" },
{ pid: 127, name: "IntlTaxFee" },
{ pid: 127, name: "FlightExchangeClassCache" },
{ pid: 127, name: "FlightDistributionRedis" },
{ pid: 127, name: "FlightSearchCacheL1AndL2" },
{ pid: 127, name: "FltBIDataserveice" },
{ pid: 127, name: "FlightIntlGDSCache" },
{ pid: 127, name: "IntlflightSalesPolicyEngine" },
{ pid: 127, name: "AggIntlOrderingAPI" },
{ pid: 127, name: "IntVacationPlatform" },
{ pid: 127, name: "FlightIntlLowerPriceCache" },
{ pid: 127, name: "FltPIIDCacheRedis" },
{ pid: 127, name: "FlightAirlineCache" },
{ pid: 127, name: "FlightIntlGDSValueAddedCache" },
{ pid: 127, name: "Fltuserprofile" },
{ pid: 127, name: "FlightIntlAirlineLowPriceCache" },
{ pid: 127, name: "FlightIntlTrainCached" },
{ pid: 127, name: "FlightSettlementWSCache" },
{ pid: 127, name: "FlightExchangeIntlClass" },
{ pid: 127, name: "FlightOrderModifyTokenCached" },
{ pid: 127, name: "FlightOrderMessageInfo" },
{ pid: 127, name: "FlightOrderList" },
{ pid: 127, name: "FlightMobileRedis" },
{ pid: 127, name: "FlightExchangeIntlClassBaseInfo" },
{ pid: 127, name: "FlightExchangeVariflightDataCache" },
{ pid: 127, name: "FlightTransitCache" },
{ pid: 127, name: "FlightMobilePushRedis" },
{ pid: 127, name: "FlightBookingAggregator" },
{ pid: 127, name: "FlightExchangeMisc" },
{ pid: 127, name: "FLTcampaign" },
{ pid: 127, name: "FlightTradeProduct" },
{ pid: 127, name: "FlightTradeConnectivityData" },
{ pid: 127, name: "FlightRouteServiceCache" },
{ pid: 127, name: "IntResourceFare" },
{ pid: 127, name: "IntResourceAddon" },
{ pid: 127, name: "IntResourceRouting" },
{ pid: 127, name: "VS_Ws.order.flight" },
{ pid: 127, name: "FlightMobileRedisIntl" },
{ pid: 127, name: "IntB2BPlatform" },
{ pid: 127, name: "IntlAggregatorProductCached" },
{ pid: 127, name: "IntlAggregatorResultCached" },
{ pid: 127, name: "FlightMobileRedisRestful" },
{ pid: 127, name: "FlightIntlOAGCache" },
{ pid: 127, name: "FlightMobileRedisFIO" },
{ pid: 127, name: "FlightEngineSearchCache" },
{ pid: 127, name: "AggBookingValidation" },
{ pid: 130, name: "FxUbt" },
{ pid: 131, name: "HotelRoomStatusCounts" },
{ pid: 131, name: "HtlVendorPriceIntl" },
{ pid: 131, name: "HtlVendorPriceRealTimeCache" },
{ pid: 131, name: "HotelWireless" },
{ pid: 131, name: "hoteldataapi" },
{ pid: 131, name: "HotelCrossSale" },
{ pid: 131, name: "HotelFarmHouseService" },
{ pid: 131, name: "Htldomestic" },
{ pid: 131, name: "htlcommentsearch" },
{ pid: 131, name: "HotelCPmsOnline" },
{ pid: 131, name: "HotelOrderTask" },
{ pid: 131, name: "HotelDirectConnectDomestic" },
{ pid: 131, name: "HotelDirectConnectOvsIn" },
{ pid: 131, name: "HotelDirectConnectOvsOut" },
{ pid: 131, name: "HtlVendorpriceintlCore" },
{ pid: 131, name: "HotelProductInput" },
{ pid: 131, name: "HotelBookingReservation" },
{ pid: 131, name: "HotelOrderProcess" },
{ pid: 131, name: "HotelProductSearchService" },
{ pid: 131, name: "HotelProductInterfaceService" },
{ pid: 131, name: "EventSaleCache" },
{ pid: 131, name: "HotelSearchCacheService" },
{ pid: 131, name: "HotelEbookingCache" },
{ pid: 131, name: "HotelBookingReservationCache" },
{ pid: 131, name: "HotelProductSeqRules" },
{ pid: 131, name: "HotelProductRoomRotary" },
{ pid: 131, name: "HotelCtripPriceCache" },
{ pid: 131, name: "HotelProductRoomPrice" },
{ pid: 131, name: "HotelProductRoomStatus" },
{ pid: 131, name: "HotelProductRoomQuantity" },
{ pid: 131, name: "HotelProduct" },
{ pid: 131, name: "HtlVendorLowestRoomPrice" },
{ pid: 131, name: "VendorComparative" },
{ pid: 131, name: "HotelHtlHPPCache" },
{ pid: 131, name: "VendorComparativeRawPrice" },
{ pid: 131, name: "HotelInternationalShadowPrice" },
{ pid: 131, name: "HotelDirectConnectDomesticMapping" },
{ pid: 131, name: "HotelDirectConnectOvsSwitch" },
{ pid: 131, name: "PersonalizeRedis" },
{ pid: 131, name: "hoteldataonline" },
{ pid: 131, name: "HotelVendorCore" },
{ pid: 131, name: "Hoteldatacache" },
{ pid: 131, name: "Hotel_usercredit" },
{ pid: 131, name: "HotelAutoBackCash" },
{ pid: 131, name: "HtlVendorPriceCache" },
{ pid: 131, name: "HotelProductInterfaceService110403" },
{ pid: 131, name: "hotel-data-userpreference" },
{ pid: 131, name: "hotel-data-ubt" },
{ pid: 131, name: "hotel-data-recommend" },
{ pid: 131, name: "hotel-data-filter" },
{ pid: 131, name: "HotelPricesCenter" },
{ pid: 131, name: "HotelSearchCacheJobDr" },
{ pid: 131, name: "HotelSearchCacheJobIntlDr" },
{ pid: 131, name: "hotel_wireless_h5" },
{ pid: 131, name: "hdataCache" },
{ pid: 131, name: "HotelProductStaticRequestInfo" },
{ pid: 133, name: "GroupProductIndex" },
{ pid: 134, name: "TrainAPICenterG1" },
{ pid: 134, name: "TrainAPICenterG2" },
{ pid: 134, name: "AirBus" },
{ pid: 134, name: "TrainCoupon" },
{ pid: 134, name: "traindataredis" },
{ pid: 134, name: "train_ticket_redis_ctrip_com" },
{ pid: 135, name: "TravelshoppingMall" },
{ pid: 136, name: "TourCacheImage" },
{ pid: 136, name: "TourCacheComputation" },
{ pid: 136, name: "TourCacheImages" },
{ pid: 136, name: "TourInventoryPriceCache" },
{ pid: 136, name: "TourCacheProductImage" },
{ pid: 136, name: "SHXpricecalendar" },
{ pid: 136, name: "SHXproductinfo" },
{ pid: 136, name: "SHXdistributionhotelinfo" },
{ pid: 136, name: "SHXdistributionroominfo" },
{ pid: 136, name: "TourCacheSearch" },
{ pid: 136, name: "SHXdistributionproduct" },
{ pid: 138, name: "Tour-Insurance" },
{ pid: 140, name: "shxdp" },
{ pid: 140, name: "meeting" },
{ pid: 141, name: "GSCommonSOACache" },
{ pid: 141, name: "GSProduct" },
{ pid: 141, name: "GSDangDiCache" },
{ pid: 141, name: "GSEventsCache" },
{ pid: 141, name: "GSMemberCache" },
{ pid: 141, name: "GSAccountCache" },
{ pid: 141, name: "GSDestinationSiteCache" },
{ pid: 141, name: "GSDestinationServiceCache" },
{ pid: 141, name: "GSSeoCache" },
{ pid: 141, name: "GSShoppingCache" },
{ pid: 141, name: "GSActivityCache" },
{ pid: 141, name: "GSPoiCache" },
{ pid: 141, name: "GSCommentCache" },
{ pid: 141, name: "GS_AskPool" },
{ pid: 141, name: "GSTravelCache" },
{ pid: 141, name: "GSWeatherCache" },
{ pid: 141, name: "GSAPICache" },
{ pid: 141, name: "GSAPPCache" },
{ pid: 141, name: "GSGeneralCache" },
{ pid: 141, name: "GSTopHotelCache" },
{ pid: 141, name: "GSBackgroundCache" },
{ pid: 141, name: "GSScheduleCache" },
{ pid: 141, name: "GSBackgroundManageCache" },
{ pid: 141, name: "GSDataSupportCache" },
{ pid: 141, name: "RemoteCrawler" },
{ pid: 141, name: "RemoteCrawlerCache" },
{ pid: 144, name: "gsphotos" },
{ pid: 144, name: "GS_Ask" },
{ pid: 146, name: "FncMobilePayWayCache" },
{ pid: 146, name: "FncUserPaymentInfo" },
{ pid: 146, name: "FncPaymentRouter" },
{ pid: 146, name: "FncUserVerificationIdNoMapRedis" },
{ pid: 146, name: "PaymentCache" },
{ pid: 146, name: "SecurePaymentCache" },
{ pid: 146, name: "FncAcctConfigCache" },
{ pid: 146, name: "FncAcctUserRelationCache" },
{ pid: 146, name: "FncPayResultCache1" },
{ pid: 146, name: "FncPaymentRealTimeCache" },
{ pid: 146, name: "FncMayFly" },
{ pid: 146, name: "FncCommStatic" },
{ pid: 146, name: "FncPWDVerificationCodeCache" },
{ pid: 146, name: "FncPWDCustomerSecurityErrorCounterCache" },
{ pid: 147, name: "GiftCardOnlineCache" },
{ pid: 147, name: "FncGCBalanceCache" },
{ pid: 147, name: "GCSurpriseStatusCache" },
{ pid: 147, name: "GCPayCache" },
{ pid: 147, name: "GCAccountCache" },
{ pid: 147, name: "FncGcConfigCenterCache" },
{ pid: 149, name: "BIProductsCache" },
{ pid: 149, name: "ModifiedUserIDs" },
{ pid: 149, name: "MyFavorite" },
{ pid: 149, name: "Ctimaili" },
{ pid: 149, name: "BaseBizChineseHomePage" },
{ pid: 149, name: "BIUserBehaviorCache" },
{ pid: 149, name: "WeixinServer" },
{ pid: 149, name: "MembersUserProfile" },
{ pid: 149, name: "VS_Ws.message.members" },
{ pid: 149, name: "BBZMemberMiscRedis" },
{ pid: 149, name: "BBZMembersCMBReport" },
{ pid: 149, name: "BBZMembersInboundParameter" },
{ pid: 149, name: "MemberUserProfile" },
{ pid: 149, name: "BBZMembersPoints" },
{ pid: 149, name: "BBZMemberCredentials" },
{ pid: 151, name: "MessagePlat" },
{ pid: 151, name: "PushMobile" },
{ pid: 152, name: "CTIUserIntention" },
{ pid: 152, name: "communication-im" },
{ pid: 153, name: "kefu_rcache" },
{ pid: 154, name: "BaseBizPushMobile" },
{ pid: 154, name: "Discovery" },
{ pid: 155, name: "TPortal.mgmt.ctripcorp.com" },
{ pid: 155, name: "CosSetDiff" },
{ pid: 155, name: "McdSession" },
{ pid: 158, name: "AffiliateMarketingRuleSets" },
{ pid: 158, name: "MKTSeo" },
{ pid: 159, name: "MKTProductCache" },
{ pid: 159, name: "MKTMessageCache" },
{ pid: 159, name: "MKTAdCacheServer" },
{ pid: 159, name: "MKTSericeMarket" },
{ pid: 159, name: "MKTLimitSpeed" },
{ pid: 159, name: "mktpromotioncodenc" },
{ pid: 159, name: "mktmqqRedPacket" },
{ pid: 159, name: "mktmqqRedPacket2" },
{ pid: 159, name: "mktmqqRedPacket3" },
{ pid: 159, name: "mktmqqRedPacket4" },
{ pid: 159, name: "mktmqqRedPacket5" },
{ pid: 159, name: "mktmqqRedPacket6" },
{ pid: 159, name: "mktmqqRedPacket7" },
{ pid: 159, name: "mktmqqRedPacket8" },
{ pid: 159, name: "mktmqqRedPacket9" },
{ pid: 159, name: "mktmqqRedPacket10" },
{ pid: 165, name: "FunDB" },
{ pid: 165, name: "FunCache" },
{ pid: 165, name: "GSGlobalFood" },
{ pid: 166, name: "Bwgcached" },
{ pid: 166, name: "UFSRedis" },
{ pid: 166, name: "LSHForOverseaHotels" },
{ pid: 169, name: "GlobalSite" },
{ pid: 169, name: "GlobalSite_EN" },
{ pid: 169, name: "GlobalSite_JP" },
{ pid: 169, name: "IBUPackagesRedis1" },
{ pid: 169, name: "IBUCommonPOI1" },
{ pid: 170, name: "AccountRiskControl" },
{ pid: 170, name: "PaymentRiskControl" },
{ pid: 170, name: "CounterServer_01" },
{ pid: 170, name: "CounterServer_02" },
{ pid: 170, name: "CounterServer_03" },
{ pid: 170, name: "userprofileinfosec" },
{ pid: 170, name: "CounterServer_04" },
{ pid: 170, name: "CounterServer_SIM" },
{ pid: 171, name: "Corp.Booking.IntlFlight" },
{ pid: 171, name: "Corp.Product.Hotel" },
{ pid: 171, name: "Corp.Mobile.SettingManage" },
{ pid: 171, name: "Corp_Mobile_SOAProxy" },
{ pid: 171, name: "Corp_Product_IntlFlight" },
{ pid: 174, name: "Members.OfflineLogin" },
{ pid: 176, name: "CruiseProduct" },
{ pid: 176, name: "Skysea" },
{ pid: 176, name: "CruiseFrontend" },
{ pid: 176, name: "CruiseOrder" },
{ pid: 177, name: "GCPayStatusCache" },
{ pid: 177, name: "FncUserPaymentPWDCache" },
{ pid: 177, name: "GCRechargeCardCode" },
{ pid: 177, name: "TaxRefundRedis" },
{ pid: 178, name: "qiche" },
{ pid: 178, name: "BUS_DATA_VENDOR" },
{ pid: 178, name: "BUS_DATA_CENTRE" },
{ pid: 178, name: "order_center_log" },
{ pid: 178, name: "BUS_DATA_TJ" },
{ pid: 178, name: "BUS_DATA_MARKETING" },
{ pid: 178, name: "qiche.vendor.async" },
{ pid: 178, name: "BUS_DATA_CRAWL" },
{ pid: 178, name: "BUS_VENDORDATA" },
{ pid: 182, name: "IBUPackagesRedis2" },
{ pid: 184, name: "Wireless_Youth" },
{ pid: 184, name: "Wireless_Ticket" },
{ pid: 185, name: "TourDingZhiPlatformService" },
{ pid: 187, name: "shxsdpcalendar" },
{ pid: 190, name: "SentinelTest1" },
{ pid: 190, name: "shilyTest" },
{ pid: 190, name: "FxAppMonitor" },
{ pid: 190, name: "TestRedis" },
{ pid: 190, name: "JavaTestCluster" },
{ pid: 190, name: "FxSentinelMonitor" },
{ pid: 190, name: "MultyIdcTest" },
{ pid: 196, name: "FncCardRedis" },
{ pid: 196, name: "FncPaymentExternalRedis" },
{ pid: 196, name: "PaymentApi" },
{ pid: 197, name: "BBZRTUserBehavior" },
{ pid: 198, name: "cciminfosec" },
{ pid: 198, name: "casClientPrincipal" },
{ pid: 198, name: "InfoSecRiskDataService" },
{ pid: 198, name: "InfoSecCaptcha" },
{ pid: 198, name: "SecSaas" },
{ pid: 205, name: "FncCardRewardsRedis" },/**/
{ pid: 4302, name: "SentinelTest3" }
        ]
    };
    var LoadConfig = function (options) {
        this.settings = $.extend({}, loadConfig_default_settings, options);
        return true;
    };

    LoadConfig.prototype.getConfigServiceList = function (successFunc, errorFunc) {
        //local test
        if (this.settings.fromDB == false) {
            if ($.isFunction(successFunc)) successFunc(this.settings.config_service);
            return;
        }

        //SendData({
        //    "url": "./Handler/ConfigAPI.asmx/GetConfigAPI",
        //    "data": { "userName": this.settings.curUser.Name, "orderBy": "" }//默认以host name排序
        //}, null, function (data) {
        //    var hisInfoList = data.data;
        //    for (var i = 0; i < hisInfoList.length; i++) {
        //        hisInfoList[i].name = _getReqName(hisInfoList[i]);
        //    }
        //    hisInfoList = _mergeItems(hisInfoList, "asc", "name", null);
        //    if ($.isFunction(successFunc)) successFunc(hisInfoList);
        //}, function (data) {
        //    SendDataError(data, errorFunc);
        //});
    };

    LoadConfig.prototype.getIDCIndex = function (successFunc, errorFunc) {
        if (this.settings.fromDB == false) {
            if ($.isFunction(successFunc)) successFunc(this.settings.config_idc);
            return;
        }
    };

    LoadConfig.prototype.getProductlineList = function (successFunc, errorFunc) {
        if (this.settings.fromDB == false) {
            if ($.isFunction(successFunc)) successFunc(this.settings.config_productline);
            return;
        }
    };

    LoadConfig.prototype.getClusterList = function (pid, successFunc, errorFunc) {
        if (this.settings.fromDB == false) {
            if ($.isFunction(successFunc)) {
                if (pid) successFunc(_getItems(this.settings.config_cluster, function (item) {
                    return item.pid == pid;
                }));
                else successFunc(this.settings.config_cluster);
            }
            return;
        }
    };




    $.loadConfig = function (options) {
        return new LoadConfig(options);
    };

    var SendDataError = function (data, errorFunc) {
        var status = data.status;
        var errorMessage = "Unknown Error!";
        if ($.isPlainObject(status) && (status.exception || status.statusCode)) {
            if (status.exception) {
                errorMessage = "[ErrorCode]：{0}<br/>{1}".Format(status.exception.errorCode, status.exception.message.htmlEncode());
            }
            if (status.statusCode != 0 && status.statusDescription) {
                errorMessage = "[StatusCode]：{0}<br/>{1}".Format(status.statusCode, status.statusDescription.htmlEncode());
            }
        }
        else {//data=xhr
            errorMessage = data.statusText;
        }
        if ($.isFunction(errorFunc)) errorFunc(errorMessage);
        else alert(errorMessage);
    }
})(jQuery);
